[DEFAULT]
#The inspection time in seconds, 0 means disabled
inspectiontime = 15

#True == show stat, False == hide stat
solves = True
subx = True
ao3 = True
ao5 = True
ao12 = True
ao50 = True
ao100 = False
ao1000 = False
average = True
mean = True
best = True
worst = True
latest = True

#The time keys for displaying subx stats
#Does nothing if sub-x is set to False
timekeys = 35,30,25,24,23,22,21,20